---
layout: post
title: Error Handling with Camel CXF-RS
date: '2013-01-24T15:00:00.000-08:00'
author: Mark Corkery
tags:
- Programming
- CXF-RS
- Camel
modified_time: '2013-10-20T14:22:34.855-07:00'
blogger_id: tag:blogger.com,1999:blog-7218688161043116845.post-1226125106123852327
blogger_orig_url: http://markcorkery.blogspot.com/2013/01/error-handling-with-camel-cxf-rs.html
---

I had an issue come up during development of a CXF-RS route that I couldn't find a solution to with a quick bit of googling (I'm no Google ninja so that's not saying much). To summarize, no matter what value I populated as the response code, the route would always return a 200 response :S<a name='more'></a><br/><br/>Basically I had a route with an onException guard. That part of the route I show below, but to summarize, if it encountered any exception it would send it to the exception processor and then stop. The cxf route itself for this demo did one thing, threw an exception.<br/><br/>[sourcecode language="xml" wraplines="false"]<br/>    &lt;jaxrs:server id=&quot;restServerLoc&quot; address=&quot;${publicAddress}&quot;&gt;<br/>       &lt;jaxrs:providers&gt;<br/>          &lt;ref bean=&quot;jaxbProvider&quot; /&gt;<br/>          &lt;ref bean=&quot;jsonProvider&quot; /&gt;<br/>       &lt;/jaxrs:providers&gt;<br/>       &lt;jaxrs:serviceBeans&gt;<br/>          &lt;ref bean=&quot;terminalLocationRest&quot; /&gt;<br/>       &lt;/jaxrs:serviceBeans&gt;<br/>    &lt;/jaxrs:server&gt;<br/><br/>    &lt;bean id=&quot;forced&quot; class=&quot;java.lang.IllegalArgumentException&quot;&gt;<br/>        &lt;constructor-arg index=&quot;0&quot; value=&quot;This is forced&quot; /&gt;<br/>    &lt;/bean&gt;<br/><br/>    &lt;bean id=&quot;exceptionProcessor&quot; class=&quot;com.kramkroc.example.support.ExceptionProcessor&quot; /&gt;<br/><br/>    &lt;camelContext xmlns=&quot;http://camel.apache.org/schema/spring&quot;&gt;<br/>    &lt;propertyPlaceholder location=&quot;ref:service-properties&quot; id=&quot;properties&quot;/&gt;<br/>    &lt;onException&gt;<br/>        &lt;exception&gt;java.lang.Exception&lt;/exception&gt;<br/>        &lt;handled&gt;<br/>            &lt;constant&gt;true&lt;/constant&gt;<br/>        &lt;/handled&gt;<br/>        &lt;to uri=&quot;bean:exceptionProcessor&quot;/&gt;<br/>        &lt;stop/&gt;<br/>    &lt;/onException&gt;<br/>    &lt;route&gt;<br/>        &lt;from uri=&quot;cxfrs://bean://restServerLoc&quot;/&gt;<br/>        &lt;throwException ref=&quot;forced&quot;/&gt;<br/>    &lt;/route&gt;<br/>&lt;/camelContext&gt;<br/>[/sourcecode]<br/><br/>The following was the bare bones of the processor I was using:<br/><br/>[sourcecode language="java" wraplines="false"]<br/>package com.kramkroc.example.support;<br/><br/>import org.apache.camel.Exchange;<br/>import org.apache.camel.Processor;<br/>import org.slf4j.Logger;<br/>import org.slf4j.LoggerFactory;<br/><br/>public class ExceptionProcessor implements Processor {<br/><br/>    private final Logger logger = LoggerFactory.getLogger(getClass());<br/><br/>    public void process(Exchange exchange) throws Exception {<br/>        try {<br/>            processException(exchange);<br/>        } catch (IllegalArgumentException e) {<br/>            logger.error(&quot;Exception Processor Called but could not find an exception to process&quot;, e);<br/>        }<br/>    }<br/><br/>    private void processException(final Exchange exchange) {<br/>        Exception exception = exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Exception.class);<br/>        logger.error(&quot;The following was caught!&quot;, exception);<br/>        logger.debug(&quot;About to Process incoming [{}]&quot;, exception.getClass().getName());<br/>        int httpResponseCode = 400;<br/>        if (exception instanceof NullPointerException) {<br/>            buildResponse(exchange, httpResponseCode, exception.getLocalizedMessage());<br/>        } else {<br/>            httpResponseCode = 500;<br/>            buildResponse(exchange, httpResponseCode, exception.getLocalizedMessage());<br/>        }<br/>    }<br/>    <br/>    private void buildResponse(Exchange exchange, final int httpResponseCode, final String requestError) {<br/>        exchange.getOut().setHeader(Exchange.HTTP_RESPONSE_CODE, httpResponseCode);<br/>        exchange.getOut().setHeader(Exchange.CONTENT_TYPE, &quot;application/json&quot;);<br/>        logger.debug(&quot;Returning Request Error [{}]&quot;, requestError);<br/>        exchange.getOut().setBody(requestError, String.class);<br/>    }<br/>}<br/>[/sourcecode]<br/><br/>Again, the problem was that in spite of setting the error response code as expected, the route was always returning a 200 response!<br/><br/>Somehow the penny dropped: what if instead of building an error the camel way, I build it the CXF way instead, I.e through the Response objects. Eureka!<br/><br/>See an example of the updated processor below:<br/><br/>[sourcecode language="java" wraplines="false"]<br/>package com.kramkroc.example.support;<br/><br/>import javax.ws.rs.core.Response;<br/><br/>import org.apache.camel.Exchange;<br/>import org.apache.camel.Processor;<br/>import org.slf4j.Logger;<br/>import org.slf4j.LoggerFactory;<br/><br/>public class ExceptionProcessor implements Processor {<br/><br/>    private final Logger logger = LoggerFactory.getLogger(getClass());<br/><br/>    public void process(Exchange exchange) throws Exception {<br/>        try {<br/>            processException(exchange);<br/>        } catch (IllegalArgumentException e) {<br/>            logger.error(&quot;Exception Processor Called but could not find an exception to process&quot;, e);<br/>        }<br/>    }<br/><br/>    private void processException(final Exchange exchange) {<br/>        Exception exception = exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Exception.class);<br/>        logger.error(&quot;The following was caught!&quot;, exception);<br/>        logger.debug(&quot;About to Process incoming [{}]&quot;, exception.getClass().getName());<br/>        int httpResponseCode = 400;<br/>        if (exception instanceof NullPointerException) {<br/>            buildResponse(exchange, httpResponseCode, exception.getLocalizedMessage());<br/>        } else {<br/>            httpResponseCode = 500;<br/>            buildResponse(exchange, httpResponseCode, exception.getLocalizedMessage());<br/>        }<br/>    }<br/>    <br/>    private void buildResponse(Exchange exchange, final int httpResponseCode, final String requestError) {<br/>        final Response r = Response.status(httpResponseCode).entity(requestError).build();<br/>        exchange.getOut().setBody(r);<br/>        logger.debug(&quot;Returning das Request Error [{}]&quot;, r);<br/>    }<br/>}<br/>[/sourcecode]